import React from 'react';

const TermsAndConditions = () => {
  return (
    <div>
      <h2></h2>
      <p>
      Welcome to Homehelper .The Homehelper Website is owned and operated by Homehelper Enterprise (herein for brevity referred to as "Homehelper"). By using or registering for anyafashions.com, users and the entities or persons they represent ("User" or "Users") agree to be legally bound and abide by the terms, conditions, and notices set forth or referenced herein and any other condition displayed on any of the pages of the Anya Website (collectively, the "Terms"). Anya reserves the right to change, alter, modify, amend these Terms, from time to time, at its sole discretion without serving any notice to you ("Modifications"). The amended terms and conditions shall override the Terms to extent any such amended term is inconsistent or repugnant to these Terms and all Users shall be bound by such amended Terms. You can review the most current version of the Terms at any time at our website. Your continued use of the Anya Website following the posting of any Modifications constitutes acceptance of the same. If you do not agree to these Terms, as amended from time to time, please do not access or avail of the Services provided or use the Anya Website. The use of the term Representatives shall include Anya's employees, sponsors, directors, officers, shareholders, representatives, subsidiaries, advertising, promotion and fulfillment agencies, consultants and advisors).</p>
      <h2></h2>
      <p>
      You agree that you are only authorized to visit, view and to retain a copy of sections/pages of the Homehelper Website for your own personal use, and that you shall not duplicate, download, publish, modify, hack, tamper with, damage the contents in any manner or otherwise distribute the information, data, software, photographs, videos, typefaces, graphics, music, sounds, and other material on the Homehelper Website (collectively "Content") for any purpose other than to review product and promotional information, or to purchase product for your personal use, unless otherwise specifically authorized by Homehelper to do so. Except as expressly authorized by the Anya Website, you agree not to sell, license, rent, modify, distribute, copy, reproduce, transmit, publicly display, publish, adapt, edit, or create derivative works from such Content. Notwithstanding the above, if no specific restrictions are displayed, you may make copies of selected portions of the Content, provided that the copies are made only for your personal, non-commercial use and provided you keep intact all copyright and other proprietary notices relating to the same. You agree that you shall not upload, post, reproduce, or distribute for commercial purposes any materials or design, text or graphics or Content on the Anya Website and further you agree that you shall not reproduce or transmit the same, in any form or by any means, electronic or mechanical or otherwise, including by photocopying, facsimile transmission, recording, re-keying or using any information storage and retrieval system without the express written permission of Homehelper. Permission may be granted only at the sole discretion of Homehelper.

</p><h2></h2>
      <p>
      In consideration of your use of on line information resources, products, web directory(ies), index(es), general materials and data, including, but not limited to, search services, suggestions and other content (including third party information, products, materials and content) (collectively, all the services provided to you the User, from time to time whether online or offline referred to as the "Services"), you represent that you are a holder of credit card/debit card or such facilities provided by banks and undertake and agree to: (i) provide true, accurate, current and complete information about yourself as prompted by the Anya Website's registration form (such information being the "Registration Data") and (ii) maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, not current or incomplete, or anyafashions.com has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, anyafashions.com has the right to suspend or terminate your account and refuse any and all current or future use of the Services (or any portion thereof). "

</p><h2>Member Account, Password and Security</h2>
<p>
You will receive a password and account information upon registering with us, and you agree that with respect to your account and password that you: are responsible for maintaining the confidentiality of your password and account are fully responsible for all activities that occur under your password or account. You will immediately notify the Anya Website of any unauthorized use of your password or account or any other breach of security; and shall be fully liable for all use of your account, including any unauthorized use of your account by any third party including the content of your transmissions through the Anya Website. Agree that you are entirely responsible for any and all activities that occur under your account and will ensure that you diligently exit from your account at the end of each session. Anya will not be liable for any loss or damage arising from any misuse of your password by any person due to any reason whatsoever. Please understand and acknowledge that Anya cannot and will not be liable for any loss or damage arising from your failure to comply with these requirements.
</p><h2>Disclaimer</h2>
<p>
The User agrees that he / she must evaluate, and bear all risks associated with, the use of any Content, including any reliance on the accuracy, completeness, or usefulness of such Content. Anya shall not be liable for any decision made or action taken by the User or others based upon reliance on information or materials obtained through use of the Service. We take cognizance of the fact that the User is acting in his or her own best interest and transacting at his or her own risk. Prior to the execution of any transactions the User should make himself / herself aware of all the terms and conditions governing the transaction.
</p><h2>Confidentiality</h2>
<p>
We ask our customers to supply personal data when placing an order, such as name, address and E-mail address. We use this data only for the purpose of filling an order, or communicating with the customer or supplier about the status of an order. We will not distribute or sell customer information to any third party, or use information for any other purpose other than what is required to perform our services. anyaonline.in agrees to keep and procure to be kept secret and confidential any and all written and/or oral information of any kind including that relating to the of the order through any conversation, meeting, discussion, and to disclose the same only to those of its officers, employees, agents, contractors or subcontractors on a need-to-know basis and only to the extent necessary for each of them to perform such service obligations. anyaonline.in is committed to safeguarding the privacy of our users' personal data.
</p><h2>Copyright Information</h2>
<p>
The graphics and content on this site are the copyright work of anyaonline.in and contain proprietary trademarks and trade names of the Company. anyaonline.in hereby authorizes copying of documents for non-commercial use or for educational research only. This copyright notice must appear on every such copy. No right or license is granted under any copyright, patent or trademark of anyaonline.in to any other party
</p>
      {/* Add more terms and conditions paragraphs as needed */}
    </div>
  );
};

export default TermsAndConditions;
